cartridge

* Create `/var/run/tarantool` dir and set its owner to `tarantool:tarantool` in RPM pre script
* Fix systemd unit files Description

Fix create user script 2

---

.gitlab-ci.yml
Makefile

Cache downloaded sdk between ci jobs

---

cartridge
test/integration/instance_management_test.lua

Colorize logs and prefix with instance name for multiple foreground instances

---

CHANGELOG.md
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
templates/cartridge/${project_name_lower}-scm-1.rockspec

Set cartridge dependency version to 1.2.0-1 in template project rockspec

Freeze cartridge 1.2.0 version in cartridge template

---

CHANGELOG.md
cartridge-cli.lua
test/integration/cartridge_test.lua

Option to display version

---

.gitlab-ci.yml

Add default section with `docker`, `mcs` tags
Move defailt image to default section

Fix automatic rockspec publishing

---

test/python/test_pack.py

Test packing with wrong filemodes

---

CHANGELOG.md
cartridge-cli.lua

Group pre-build, build and post-build actions in one RUN directive

Run all build actions in one layer

---

CHANGELOG.md
cartridge-cli.lua
test/python/project.py

Fix error on submodules cleanup

---

.luacheckrc
CHANGELOG.md
cartridge-cli.lua
test/python/project.py
test/python/test_create.py

See @olegrok [suggestion](https://github.com/tarantool/cartridge-cli/pull/116#discussion_r368242804)

Refactor error handling on `pack` and `create`

---

cartridge-cli.lua

Now form_distribution_dir performs all actions required for
creation distribution directory:
* copying application files;
* cleanning it up (remove .rocks, .git, ignored etc.)
* building application;
* cleanning up after the build;
* generating VERSION file.

Refactor form_distribution_dir function

---

CHANGELOG.md
README.md
cartridge-cli.lua
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
templates/cartridge/cartridge.post-build
templates/cartridge/deps.sh
test/python/conftest.py
test/python/project.py
test/python/test_build.py
test/python/test_pack.py

Cartridge build command

---

cartridge-cli.lua
test/python/test_build.py
test/python/test_create.py
test/python/test_docker_pack.py
test/python/test_pack.py
test/python/utils.py

Capture errors output to check that command fail reason is right

Improve negative tests

---

cartridge-cli.lua

Fix Tarantool 2.1 repo version compution

---

CHANGELOG.md
Makefile
cartridge-cli.lua
test/python/test_docker_pack.py
test/python/test_pack.py
test/unit/dockerfile_constructors.lua

Pack application in docker

---

cartridge-cli.lua

* Use pcall to handle internal errors on app creation and packing
* Format internal error messages

Improve internal errors handling

---

test/python/conftest.py
test/python/test_pack.py
test/python/test_pack_docker.py
test/python/test_pack_e2e.py
test/python/utils.py

* Separate e2e tests for pack in a module
* Test running application from tgz packed in docker

Improve python e2e tests

---

test/python/project.py
test/python/test_pack.py

Skip packing in docker tests for deprecated projects

Skip some tests

---

.gitlab-ci.yml
CHANGELOG.md
README.md
cartridge-cli.lua
test/python/test_pack.py
test/python/test_pack_docker.py
test/unit/dockerfile_constructors_test.lua
test/unit/sdk_path_detection_test.lua

Build in docker reworks

---

.gitlab-ci.yml
test/helper.lua
test/integration/cartridge_test.lua
test/integration/instance_management_test.lua
test/python/conftest.py
test/python/project.py
test/python/test_build.py
test/python/test_create.py
test/python/test_pack.py
test/python/test_pack_docker.py
test/python/test_pack_e2e.py
test/python/utils.py

Compile cartridge executable and use it as a fixture in all tests

Use compiled executable in tests

---

README.md
cartridge-cli.lua
test/python/test_pack.py

Add suffix option for pack command

---

README.md
cartridge-cli.lua

Drop `pack rock`

---

examples/getting-started-app/README.md

The doc on site is outdated and doesn't have appropriate section.

Fix link in getting started readme

---

CHANGELOG.md
cartridge-cli.lua
cartridge-cli/utils.lua
test/integration/instance_management_test.lua

Prettify `cartridge start/stop` logs

---

CHANGELOG.md
cartridge-cli.lua
cartridge-cli/utils.lua

Closes #230 
Archive data was stored in a Lua string. 
Now all archives data is stored in a files.

Do not save archives data in lua memory

---

CHANGELOG.md
README.md
cartridge-cli.lua
test/helper.lua
test/integration/start_stop_stateboard_only_test.lua
test/integration/start_stop_test.lua
test/integration/start_stop_with_stateboard_test.lua
test/integration/status_test.lua

Add `cartridge status` command
Improve `start/stop` logs using instance status

Improve checking instance status

---

.gitlab-ci.yml

Added deploy-repo-manual job for uploading distribs into download.tarantool.org

Upload packages on download.tarantool.org

---

CHANGELOG.md
cartridge-cli.lua
test/python/test_pack_docker.py

Image is tagged as `<appname>:<version>[-<suffix>]`

Fix image fullname

---

test/python/test_pack_docker.py

Add missed suffix to expected fullname

Fix result image fullname tests

---

examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md

* Update readme_rus.md according to getting-started-app code
* Fix typo at readme.md

Fix getting-started readme.md and readme_rus.md

---

cartridge-cli.lua
test/python/test_pack_docker.py

Don't detect project version if --tag is specified

---

cli/build/docker.go
cli/commands/pack.go
cli/docker/build.go
cli/docker/run.go
cli/pack/common.go
cli/pack/common_test.go
cli/pack/docker.go
cli/pack/pack.go
cli/project/project.go

Support --cache-from, --no-cache and multiple --tag options

Rewrite in Go: Docker options

---

cli/commands/start.go
cli/commands/status.go
cli/commands/stop.go
cli/pack/pack.go
cli/running/common.go
cli/running/common_test.go
cli/running/running.go
test/examples/test_getting_started.py
test/integration/test_running.py
test/utils.py

Rewrite in Go: Simplify start

---

CHANGELOG.md
cli/build/local.go
cli/build/post_build.go
test/integration/test_pack.py

Fix error on packing without hooks

---

CHANGELOG.md
cli/docker/build.go
cli/docker/build_test.go

Fix build in docker error

---

README.rst
cli/commands/common.go
cli/commands/common_test.go
cli/commands/start.go
cli/context/context.go
cli/running/process.go
cli/running/processes_set.go
cli/running/running.go
go.mod
test/conftest.py
test/integration/test_running.py
test/project.py
test/utils.py

`--timeout` option for `start` command

---

CHANGELOG.md
README.rst
cli/commands/log.go
cli/commands/start.go
cli/common/utils.go
cli/common/utils_test.go
cli/context/context.go
cli/running/process.go
cli/running/processes_set.go
cli/running/running.go
go.mod
test/integration/test_log.py
test/project.py
test/utils.py

Log command

---

CHANGELOG.md
cli/create/templates/app_files.go
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
examples/getting-started-app/getting-started-app-scm-1.rockspec
test/integration/test_create.py

See https://github.com/tarantool/cartridge/releases/tag/2.2.1

Update cartridge in app template to 2.2.1

---

.goreleaser.yml
magefile.publish.go

Fix package names

---

cli/commands/cartridge.go
cli/commands/common.go
cli/commands/repair.go
cli/commands/usage.go
cli/common/files.go
cli/common/result.go
cli/context/context.go
cli/repair/advertise_uri.go
cli/repair/clusterwide_config.go
cli/repair/common.go
cli/repair/repair.go
go.mod
test/clusterwide_conf.py
test/conftest.py
test/integration/test_repair.py
test/integration/test_repair_set_uri.py
test/utils.py

Repair: Set URI

---

cli/commands/repair.go
cli/common/utils.go
cli/context/context.go
cli/repair/clusterwide_config.go
cli/repair/remove.go
cli/repair/repair.go
test/conftest.py
test/integration/test_repair.py
test/integration/test_repair_remove_instance.py

Repair: Remove Instance

---

cli/commands/repair.go
cli/context/context.go
cli/repair/repair.go
cli/repair/set_leader.go
test/conftest.py
test/integration/test_repair.py
test/integration/test_repair_set_leader.py

Repair: Set Leader

---

CHANGELOG.md

Release 2.2.1

---

cli/common/result.go
cli/repair/advertise_uri.go
cli/repair/common.go
cli/repair/remove.go
cli/repair/repair.go
cli/repair/set_leader.go

Refactor Repair Messages

---

cli/commands/repair.go
cli/repair/list.go
cli/repair/repair.go
test/integration/test_repair_list_topology.py

Repair: List Topology

---

cli/repair/clusterwide_config.go
cli/repair/clusterwide_config_test.go
cli/repair/remove.go

Repair: Unit tests

---

cli/common/utils.go
cli/repair/clusterwide_config.go
cli/repair/clusterwide_config_test.go
test/clusterwide_conf.py
test/conftest.py
test/integration/test_repair_remove_instance.py
test/integration/test_repair_set_leader.py
test/integration/test_repair_set_uri.py

Repair: Old Clusterwide Config 

---

cli/commands/repair.go
cli/context/context.go
cli/repair/advertise_uri.go
cli/repair/repair.go
test/conftest.py
test/integration/test_repair_set_uri.py

Repait: Change Set URI args

---

cli/common/result.go
cli/repair/common.go
cli/repair/repair.go
test/clusterwide_conf.py
test/integration/test_repair.py
test/integration/test_repair_list_topology.py
test/integration/test_repair_remove_instance.py
test/integration/test_repair_set_leader.py
test/integration/test_repair_set_uri.py
test/utils.py

Repair: Refactoring

---

cli/commands/common.go
cli/commands/usage.go
cli/context/context.go
cli/repair/advertise_uri.go
cli/repair/app_configs.go
cli/repair/clusterwide_config.go
cli/repair/clusterwide_config_test.go
cli/repair/common.go
cli/repair/list.go
cli/repair/remove.go
cli/repair/repair.go
cli/repair/set_leader.go
test/integration/test_repair_diverged_config.py
test/integration/test_repair_list_topology.py
test/integration/test_repair_remove_instance.py
test/integration/test_repair_set_leader.py
test/integration/test_repair_set_uri.py
test/utils.py

Repair: Diverged Config

---

cli/common/result.go
cli/repair/clusterwide_config.go
cli/repair/list.go
cli/repair/repair.go
test/integration/test_repair_diverged_config.py
test/integration/test_repair_list_topology.py
test/utils.py

Order UUIDs in topology summary

---

cli/commands/common.go
cli/commands/completion.go
cli/commands/repair.go
cli/repair/completion.go
cli/repair/completion_test.go

We like shell completions. Let's use it for repair.

Repair: Completion

---

cli/commands/common_test.go
cli/docker/build_test.go
cli/pack/common_test.go
cli/project/dockerfiles_test.go
cli/rpm/lead_test.go
cli/rpm/tagset_test.go
cli/running/common_test.go
cli/running/process_test.go

I've just figured out that go unit tests can be ran in parallel.

Run unit test in parallel

---

README.rst
cli/commands/common.go

Repair: Documentation

---

CHANGELOG.md
cli/create/templates/app_files.go
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
examples/getting-started-app/getting-started-app-scm-1.rockspec
test/integration/create/test_create.py

Update cartridge to 2.3.0

---

CHANGELOG.md
cli/create/templates/app_files.go
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
examples/getting-started-app/getting-started-app-scm-1.rockspec
test/integration/create/test_create.py

Metrics version updated

---

CHANGELOG.md

Cartridge Admin: Changelog

---

README.rst
doc/admin.rst

Cartridge Admin: Doc

---

CHANGELOG.md
README.rst
cli/admin/admin.go
cli/admin/call.go
cli/admin/common.go
cli/admin/help.go
cli/admin/list.go
cli/admin/utils.go
cli/commands/admin.go
cli/commands/common.go
cli/commands/usage.go
cli/common/socket.go
cli/context/context.go
cli/create/templates/app_files.go
cli/create/templates/config_files.go
doc/admin.rst
test/conftest.py
test/files/init_admin_funcs.lua
test/integration/admin/test_call.py
test/integration/admin/test_common.py
test/integration/admin/test_default.py
test/integration/admin/test_help.py
test/integration/admin/test_list.py
test/project.py
test/utils.py

Cartridge Admin

---

cli/commands/replicasets.go
cli/commands/usage.go
cli/common/result.go
cli/common/utils.go
cli/context/context.go
cli/create/templates/dev_files.go
cli/replicasets/edit_topology.go
cli/replicasets/expel.go
cli/replicasets/expel_test.go
cli/replicasets/failover_priority_test.go
cli/replicasets/join_test.go
cli/replicasets/roles_test.go
cli/replicasets/save.go
cli/replicasets/setup.go
cli/replicasets/setup_test.go
cli/replicasets/topology_replicasets.go
cli/replicasets/weight_test.go
test/integration/replicasets/conftest.py
test/integration/replicasets/test_setup.py
test/utils.py

Commands that allows to manage topology described in a file..
This is the second part of #396 

Manage Topology: File

---

cli/commands/replicasets.go
cli/common/result.go
cli/replicasets/common.go
cli/replicasets/join.go
cli/replicasets/list.go
cli/replicasets/list_test.go
cli/replicasets/setup.go
cli/replicasets/topology_replicasets.go
test/integration/replicasets/conftest.py
test/integration/replicasets/test_list_replicasets.py
test/integration/replicasets/utils.py

Topology management: List

---

cli/common/socket.go
cli/common/tarantool.go
cli/replicasets/bootstrap_vshard.go
cli/replicasets/common.go
cli/replicasets/edit_topology.go
cli/replicasets/setup.go
go.mod
test/integration/repair/test_repair_reload.py
test/integration/replicasets/conftest.py
test/project.py

Topology Management: Old Cartridge Support

---

CHANGELOG.md

Topology Management: Changelog

---

README.rst

Fix pipeline status badge

---

cli/common/socket.go
cli/common/socket_test.go

This is required for #419.
Enter and connect command use Tarantool connection eval to get a list of suggestions.
Since we support Lua output, we should be able to parse results in this format.
Both `EvalTarantoolConnLua` and `EvalTarantoolConnYAML` functions are used by Cartridge CLI,
so it shouldn't fail on returning non-serializeable data (until somebody write such code in Cartridge CLI,
but in this case, CLI returns internal error).

Eval Tarantool connection w/ Lua output

---

cli/project/files.go

Refactor instance files names compution

---

CHANGELOG.md
README.rst
cli/commands/connect.go
cli/commands/usage.go
cli/common/utils.go
cli/connect/binary.go
cli/connect/common.go
cli/connect/connect.go
cli/connect/console.go
cli/connect/plain_text.go
cli/context/context.go
doc/connect.rst
go.mod
test/integration/connect/conftest.py
test/integration/connect/test_connect.py
test/integration/connect/test_enter.py
test/integration/connect/utils.py

Enter and Connect commands

---

CHANGELOG.md
cli/admin/call.go
cli/create/templates/app_files.go
doc/admin.rst
test/files/init_admin_funcs.lua
test/integration/admin/test_call.py
test/integration/admin/test_list.py

Print pushed messages on admin call

---

CHANGELOG.md
cli/create/templates/cartridge/replicasets.yml
cli/create/templates/cartridge/{{ .Name }}-scm-1.rockspec
test/integration/replicasets/test_list_replicasets.py
test/integration/replicasets/test_roles.py

Update template app dependencies

---

cli/replicasets/setup.go

When topology is set up from scratch and `--bootstrap-vshard` flag is
specified, setup often failed wtih "no remotes with `vshard-router` role
available" error. It happens when `vshard-router` replicaset is created
the last (exactly before vshard bootstrapping). This patch adds a
little retry on `bootstrapVshard` function call to prevent this error.

Retry on vshard bootstrapping when setup is called

---

CHANGELOG.md
cli/repair/clusterwide_config.go
cli/repair/clusterwide_config_test.go
cli/repair/list.go

Fix parsing clusterwide config with empty roles list

---

CHANGELOG.md
cli/admin/call.go
test/integration/admin/test_call.py

Parse 'number' args correclty on admin call

---

cli/connector/binary.go
go.mod

Use FZambia/tarantool v0.1.1

---

CHANGELOG.md
cli/create/templates/cartridge/{{ .Name }}-scm-1.rockspec
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
examples/getting-started-app/getting-started-app-scm-1.rockspec
test/integration/create/test_create.py

`metrics` version updated to 0.6.1

Updated metrics to 0.6.1

---

test/integration/replicasets/test_list_replicasets.py
test/integration/replicasets/utils.py
test/utils.py

Add test for replicasets list with zones

---

CHANGELOG.md
cli/create/templates/cartridge/init.lua
cli/create/templates/cartridge/{{ .Name }}-scm-1.rockspec
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
examples/getting-started-app/getting-started-app-scm-1.rockspec
test/integration/create/test_create.py

Metrics version is updated to 0.7.0. 
Default endpoint configuration for metrics and health check added to template.

Default metrics and health check endpoints in template

---

cli/commands/start.go

Fixed bug of unjustified warning for the ``--timeout`` key

Fixed bug of unjustified warning for the --timeout key

---

CHANGELOG.md
cli/connector/binary.go
go.mod

Fix binary connector error

---

.github/workflows/bump-homebrew-formula.yml
.github/workflows/release.yml

Bump Homebrew formula only on pushing tags

---

README.rst

Documentation update: elaborate on instances.yml parameters in the ``start --cfg`` section.

gh-1520 instance.yml parameters

---

CHANGELOG.md

Release 2.7.2

---

test/utils.py

Flaky tests fixed with a ``sleep`` (temporarily). See #519

Fix flaky tests

---

CHANGELOG.md
cli/commands/pack.go
test/integration/pack/test_pack.py

Pack type case insensitive

---

CHANGELOG.md
cli/create/templates/cartridge/{{ .Name }}-scm-1.rockspec

Update cartridge to 2.6.0, metrics to 0.8.0

---

README.rst

Fix broken link (build Tarantool from source) in README

---

CHANGELOG.md
cli/create/templates/cartridge/init.lua
test/files/init_admin_funcs.lua
test/integration/connect/test_connect.py
test/utils.py

Remove setting `cluster_cookie` from app template

---

CHANGELOG.md
cli/create/templates/cartridge/{{ .Name }}-scm-1.rockspec
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
examples/getting-started-app/getting-started-app-scm-1.rockspec
test/integration/create/test_create.py

Updated metrics to 0.9.0 in template

---

cli/create/templates/cartridge/app/roles/custom.lua

Fix typo in template

---

cli/commands/pack.go
cli/pack/pack.go
test/integration/pack/test_pack.py

Remove redundant warning when packing tgz or docker

---

CHANGELOG.md
README.rst
cli/pack/app_dir.go
test/e2e/test_tgz.py
test/files/init_roles_reload_allowed.lua
test/files/router_with_eval.lua
test/integration/connect/conftest.py
test/integration/connect/test_connect.py
test/integration/pack/test_pack.py
test/project.py

``cartridge pack`` generates ``VERSION.lua`` file with 
the current version of project. Closes #528

Pack command generate VERSION.lua file

---

.github/workflows/tests.yml
test/conftest.py
test/integration/pack/test_pack_docker.py

CI: Added docker image caching

---

magefile.publish.go

Push packages for ubuntu bullseye

---

.github/workflows/pull-translation.yml
.github/workflows/push-translation.yml
.github/workflows/upload-translations.yml
.gitignore
doc/README.md
doc/cleanup.py
doc/conf.py
doc/crowdin.yaml
doc/locale/ru/LC_MESSAGES/README.po
doc/locale/ru/LC_MESSAGES/doc/admin.po
doc/locale/ru/LC_MESSAGES/doc/connect.po
doc/locale/ru/LC_MESSAGES/doc/replicasets.po
doc/requirements.txt

- add crowdin.yaml
- add pull-translation.yml, push-translation.yml and upload-translations.yml to manipulate translations
- conf.py for sphinx
- add requirements.txt with packages for doc build
- modify .gitignore for doc builds
Closes #569

Add documentation translation workflows and configs

---

cli/common/lua.go
cli/pack/app_dir.go
cli/version/version.go
test/integration/cli/test_version.py

Remove unnecessary warns if project containing duplicate rocks

---

README.rst

Add release badge at README

---

README.rst

Updated build status link in README

---

test/e2e/test_deb.py
test/e2e/test_rpm.py
test/utils.py

CI: Add missing asserts and socket file checks

---

.github/workflows/tests.yml
CHANGELOG.md
cli/common/tarantool.go
cli/common/tarantool_test.go
magefile.go

Fix tarantool verison regexp

---

.github/workflows/upload-translations.yml
README.rst
doc/conf.py

What has been done? Why? What problem is being solved?
Closes #581
https://tarantool-develop.herokuapp.com/en/doc/cartridge-cli-translate-readme/book/cartridge/cartridge_cli/
https://tarantool-develop.herokuapp.com/ru/doc/cartridge-cli-translate-readme/book/cartridge/cartridge_cli/
(https://github.com/tarantool/doc/actions/runs/993647374)

Proofread the README

---

test/e2e/test_tgz.py

See #650 comments about closing the ticket.
- Changelog (change is minor)
- Documentation (not needed)
Follows up #650

Fix image name in tests

---

.github/workflows/push-translation.yml

Temporarily disable Crowdin CI/CD.

Run push-translations on workflow dispatch only

---

magefile.publish.go

publish: add new Ubuntu releases to the publish list

---

CHANGELOG.md
cli/create/templates/cartridge/{{ .NameToLower }}-scm-1.rockspec
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
examples/getting-started-app/getting-started-app-scm-1.rockspec
test/integration/cli/test_version.py
test/integration/create/test_create.py

Update cartridge to 2.7.4 and metrics to 0.13.0

---

cli/cluster/instances.go
cli/cluster/membership.go

cartridge cli performs some commands via connection
to cluster member control socket. When it looks for
an instance to connect to it does not filter out remote
instances. But such instances do not have sockets on the
system where cartridge cli is invoked.
The solution is to use only local instances to perform
any operations.
Resolves #697

Fix errors on cartridge cli different commands

---

CHANGELOG.md

Added changelog note about the fix for "Failed to dial" errors.

Add changelog notes

---

cli/common/tarantool.go

version: fix parsing Cartridge version

---

CHANGELOG.md
cli/create/templates/cartridge/init.lua

Set `compat.fiber_slice_default` to `new` by default

---

CHANGELOG.md
cli/create/templates/cartridge/{{ .NameToLower }}-scm-1.rockspec
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
examples/getting-started-app/getting-started-app-scm-1.rockspec
test/integration/cli/test_version.py
test/integration/create/test_create.py

app-dependency: update cartridge to 2.7.9

---

CHANGELOG.md
cli/common/utils.go
cli/common/utils_test.go
cli/connect/connect.go
cli/replicasets/expel.go
cli/replicasets/failover_priority.go
cli/replicasets/join.go
cli/running/running.go

Added support for instance names:
* Application name as instance name
* Instance name with dots
Closes #763

bugfix: specifying confusing instance names

---

test/integration/repair/test_repair_set_leader.py
test/requirements.txt
test/utils.py

Bumped pyyaml and flake8 versions.
Fixed flake 8 errors.

test: update requirements

---

CHANGELOG.md
cli/create/templates/cartridge/{{ .NameToLower }}-scm-1.rockspec
examples/getting-started-app/README.md
examples/getting-started-app/README_RUS.md
examples/getting-started-app/getting-started-app-scm-1.rockspec
test/integration/cli/test_version.py
test/integration/create/test_create.py

app-dependency: update Cartridge to 2.8.4

---

cli/project/dockerfiles.go

Added close of the file to CheckBaseDockerfile function.
Found by Svacer

project: add close of the file
