tarantool/cartridge-cli

- examples/getting-started-app/README.md
- examples/getting-started-app/README_RUS.md
Fix project url in `git clone` commands in getting-started-app example
READMEs
> Fix project url in getting-started-app READMEs

- cartridge-cli.lua
Rpm prior to centos8 used to ignore wrong integer sizes in the header
structure. Latest rpm installer is stricter about this, and causes the
following error if installing packages made with cartridge-cli on
centos8:
error: demo-0.1.0-0.rpm: tag[23]: BAD, tag 1033 type 5 offset 15488 count 255 len 1020
This is because FILERDEVS structure (code 1033) is INT32 while the
spec says that it should be INT16.
> Fix rpm build on centos8 by correcting header structure

- .gitlab-ci.yml
- CHANGELOG.md
- Dockerfile
- Dockerfile.cache
- Makefile
- README.md
- cartridge-cli.lua
- test/python/requirements.txt
- test/python/test_create.py
- test/python/test_pack.py
- wrapdocker
* `cartridge pack docker ./myapp` provides docker image (more details in #18)
* Build (`.cartridge.pre` + `rocks make`) is performed inside the container.
* For Tarantool Enterprise `--download_token` argument or `TARANTOOL_DOWNLOAD_TOKEN` env variable is required to download SDK (and I have no idea how to run tests correctly in this case, now it requires setting `TARANTOOL_DOWNLOAD_TOKEN` env variable to run tests for Enterprise).
* Tarantool (or bundle) version is detected from environment.
* Tarantool enterprise bundle is placed in `/usr/share/tarantool-enterprise` directory (added to `PATH`).
* Gitlab CI tests are running in centos-dind image stored on Gitlab Registry and built on `prebuild` stage.
* `TARANTOOL_DOCKER_BUILD_ARGS` is added to specify `docker build` options for  `docker …
> Pack docker

- CHANGELOG.md
- cartridge-cli.lua
- test/python/test_pack.py
Check if application source code files has at least a+r (regular files) or a+rx (directiries) permissions on application packing
Set 644 root:root for /usr/lib/tmpfs/${name}.conf and
/etc/systemd/system/${name}[@].service
Refactor tests to check files modes and owners
Add docker e2e test
> Fix modes and owners

- CHANGELOG.md
- README.md
- cartridge-cli.lua
- templates/cartridge/Dockerfile.cartridge
- test/python/test_pack.py
Implemented `--from` option for `docker pack` command (by default `Dockerfile.cartridge` is used)
It allows to install some application-specific tools on the result image
Added `Dockerfile.cartridge` to the `cartridge` template
> Support Dockerfile from option

- cartridge-cli.lua
- test/python/test_pack.py
Run `git clean` only if .git directory exists
> Fix error on packing application w/o git

- CHANGELOG.md
- cartridge-cli.lua
- test/python/test_pack.py
Don't use `luarocks` module to find and parse manifest file
Write Tarantool version for opensource
Improve tests
XXX: doesn't work for packing to docker
closes #80
> Fix rocks manifest error on packing

- CHANGELOG.md
- README.md
- cartridge-cli.lua
- templates/cartridge/.cartridge.ignore
- templates/cartridge/cartridge.post-build
- templates/cartridge/cartridge.pre-build
- test/python/conftest.py
- test/python/test_docker_pack.py
- test/python/test_pack.py
- test/python/utils.py
Fix backward compatible with `.cartridge.ignore + .cartridge.pre` 
Support new  Use `cartridge.pre-build` and `cartridge.post-build` files to specify additional actions to be done before and after `tarantoolctl rocks make`
Separate docker packing tests
Use parametrized `project` fixture to test both original and deprecated flows
Use coloured error, warn and log messages
Closes #86
> New pack flow

- CHANGELOG.md
- README.md
- cartridge-cli.lua
- templates/cartridge/cartridge.post-build
- templates/cartridge/cartridge.pre-build
- test/python/conftest.py
- test/python/test_docker_pack.py
Support deprecation flow and a new flow as well
On `cartridge pack` call check which flow is used, warn on deprecated
flow and check if only ine flow special filws are exists
Pass deprecated_build_flow flag to pack funtions
Deny using deprecated (`.cartridge.ignore` and `.cartridge.pre`) files for `pack docker`
Update README
Add deprecated_project fixture to test if it works correctly
> Support deprecated packing flow

- CHANGELOG.md
- cartridge-cli.lua
Currently if an app has submodules, the 'git clean' stage that we do
in cartridge-cli doesn't touch them, which leads to garbage
accumulating in the resulting package. Sometimes it may even lead to
failed compilation (e.g. when using CMake due to leftover
CMakeCache.txt).
This patch adds recursive cleaning of submodules during packing.
> Do 'git clean' on submodules during packing

- CHANGELOG.md
- cartridge-cli.lua
- test/python/conftest.py
- test/python/test_pack.py
- test/python/utils.py
pack: extend custom version with git commit
This patch allows to pass version as "major.minor.patch-count-hash"
Now user can pass `cartridge pack rpm --version 1.2.3-1-g8bce594e` and get rpm with name `project-1.2.3-1-g8bce594e.rpm`
Also hash is an optional argument and could be omitted: `cartridge pack rpm --version 1.2.3-1` -> `project-1.2.3-1.rpm`
Closes #113
> pack: extend custom version with git commit

- .gitlab-ci.yml
- CHANGELOG.md
- cartridge-cli.lua
- test/python/test_pack.py
- test/python/utils.py
The new (4.14.2) RPM version used in centos:8 image requires
PAYLOADDIGEST tag in package header.
This patch adds PAYLOADDIGEST and PAYLOADDIGESTALGO tags to package
header to prevent package signature check fail
> Fix RPM header for centos:8

- cartridge-cli.lua
After bed66e7234515eb06d192c4eff4cc04348022b03
cartridge-cli supports `git describe` version format.
Let's reuse `normalize_version` function and drop a piece of redundant code
> refactoring: simplify detect_git_version function

- CHANGELOG.md
- cartridge-cli.lua
This is the first part of impementing #98
Since application packing has more and more parameters (such as `name`, `version` or `deprecated_flow`), their propagation looks uglier.
@olegrok suggested storing all these parameters in the global variable, and we implemented this for `deprecated_flow` flag. But packing application in docker requires additional parameters, so I decided to store all common packing flow parameters in the global variable `pack_state`. Some parameters, specific for distribution type, are still propagated by options.
> Store common packing parameters in global variable

- cartridge-cli.lua
- test/python/conftest.py
- test/python/project.py
- test/python/test_pack.py
This patch fixes an error in case when there is `.git` file in the project root, and it's not a directory.
> Check if .git is a directory

- cartridge-cli-scm-1.rockspec
When tarantool is installed outside /usr/local, cmake encounters
problems finding it. To determine the path it uses TARANTOOL_DIR hint,
which is passed from the rockspec external_dependencies.
> Fix tarantool headers lookup

- .gitlab-ci.yml
- CHANGELOG.md
- README.md
- cartridge-cli.lua
- test/python/conftest.py
- test/python/test_pack.py
This is the second part of impementing #98.
* By default, temporary directory for application building is created in
`~/.cartridge/tmp`
* User can specify custom build directory for project in `CARTRIDGE_BUILDDIR`
environment variable. If this directory doesn't exists, it will be created, used
for building the application and then removed.
* If directory already exists, `CARTRIDGE_BUILDDIR/build.cartridge` repository 
will be used for build.
> Allow to specify build directory

- CHANGELOG.md
- README.md
- cartridge-cli.lua
- test/python/test_build.py
- test/python/test_pack.py
Allow to run `cartridge pack <type>` in the project directory without specifying path `.`.
> Add default path to cartridge pack command

- CHANGELOG.md
- README.md
- cartridge-cli.lua
- test/integration/instance_management_test.lua
- test/python/test_pack.py
- test/unit/parse_command_args.lua
This PR solves next problem: if you want to pass some boolean option (e.g. `daemonize`) to `cartridge` CLI, you should do it this way:
```bash
cartridge start --run_dir ${RUN_DIR} --daemonize  # OK
cartridge start --daemonize --run_dir ${RUN_DIR}  # FAIL
```
The second command (with boolean option passed not at the end of input) will fail because internal `argparse` module that is used in `cartridge-cli` doesn't support this feature.
Now, there is internal `argparse` wrapper that rearranges boolean options to be parsed correctly.
Moreover, is supports arguments schema, that allows to parse positional args as well as options.
```lua
parse_command_args('--name NAME --debug TYPE PATH', {
opts = {
name = 'string',
debug = 'boolean',
},
args = {
'type',
'path',
}
})
-- wil return
{
name = …
```
> Improve parsing commands args

- CHANGELOG.md
- cartridge-cli.lua
- templates/cartridge/Dockerfile.build.cartridge
- templates/cartridge/Dockerfile.cartridge
- test/python/test_docker_pack.py
- test/python/test_pack.py
- test/unit/dockerfile_constructors.lua
Use --build-from option to specify build image base layers on building in
docker
Use --from option to specify runtime imgae base layers on packing to
docker
Tests
See [coment](https://github.com/tarantool/cartridge-cli/issues/98#issuecomment-584737756) for details.
> Add --build-from option

- templates/cartridge/init.lua
To avoid clashing with system-wide installed packages, app_dir
should be the first in package.path list.
> Fix template package.path priority

- cartridge-cli.lua
- test/python/test_pack_docker.py
The Dockerfile path must be to a file within the build context.
See the [doc](https://docs.docker.com/engine/reference/commandline/build/#text-files).
`cartridge-cli` used  dockerfiles placed in the tmpdir, so building in docker didn't work on some versions of `docker`.
> Place Dockerfile in build context

- cartridge-cli.lua
* base image size: 573MB(git) -> 510MB(git-core)
* download size:    73 M(git)     -> 56 M(git-core)
* installed size:     222 M(git)   -> 69 M(git-core)
> Use git-core instead of git in base image

- Dockerfile
Use centos:7 as a base image instead of centos:8 for building Gitlab CI
image
> Fix prebuild

- README.md
others were replaced by higher level headings  
We need to have lone first-level header in markdown for proper conversion into other formats like rst.
> Made only one first-level heading

- CHANGELOG.md
- README.md
- Vagrantfile
- cartridge-cli.lua
- test/e2e/cleanup.sh
- test/e2e/start-deb.sh
- test/e2e/start-rpm.sh
- test/e2e/test-cluster.sh
RPM and DEB packages use special scripts  (pre- and post-install for package itself, 
ExecStartPre for systemd services). It requires using absolute paths for commands
like `mkdir`, `chown`, etc. As a result, package becomes platform-dependent (different
paths for binaries). This patch calls `/bin/sh` in scripts explicitly to trigger PATH lookup.
It allows to write `/bin/sh -c 'mkdir -p /my/dir'` without `mkdir` absolute path.
> Make RPM and DEB packages less platform-dependent

- CHANGELOG.md
- cartridge-cli.lua
Packing doesn't fail on `git clean` error, just prints warning messages
> Make git error not fatal

- CMakeLists.txt
Place temporary cartridge binary in
${CMAKE_CURRENT_BINARY_DIR} directory
> Don't use mktemp on build

- compile_executable.lua
Pass chunkname to `load` function: `@<filename>`
As a result, errors will contain correct <filename> and string number
> Improve executable compiling

- README.md
- cartridge-cli.lua
- cartridge-cli/templates/cartridge/files/app_files.lua
- test/python/project.py
- test/python/test_pack.py
- test/python/utils.py
This is the first part of #187 (see also https://github.com/tarantool/cartridge/issues/714)
Add `stateboard.init.lua` to template
Use `cartridge == scm-1`
Add stateboard unit file in RPM/DEB systemd directory
Test that this file is created
> Deliver app stateboard in RPM/DEB

- test/python/requirements.txt
- test/python/utils.py
Fix flake8 3.8.1 version
Don't use ambiguous variable name in tests
> Use flake8 3.8.1

- cli/pack/pack.go
- test/integration/test_pack.py
All types except tgz requires init.lua in the project root
> Rewrite in Go: Check entrypoint on pack

- cartridge-cli/templates/cartridge/files/app_files.lua
According to: https://github.com/tarantool/metrics/issues/73
New metrics role allows users to manage metrics with configuration files and enables default metrics on start of the app.
> new metrics role in template project

- cli/commands/build.go
- cli/commands/cartridge.go
- cli/commands/common.go
- cli/commands/const.go
- cli/commands/create.go
- cli/commands/log.go
- cli/commands/pack.go
- cli/commands/start.go
- cli/commands/status.go
- cli/commands/stop.go
- cli/commands/usage.go
- cli/commands/validate.go
- cli/commands/version.go
- cli/pack/validate.go
- test/integration/test_version.py
This is the preparation step for #282 
* Make *Cmd variables non-global to avoid copy-paste errors
* Move all flags usage to the separated file
* Add function for flags configuring
* Add functions for adding common flags
* Move default values to the separated file
* Support -v and --version
> Refactor command flags

- CHANGELOG.md
- README.rst
- cli/commands/stop.go
- cli/commands/usage.go
- cli/context/context.go
- cli/running/process.go
- cli/running/processes_set.go
- cli/running/running.go
- test/conftest.py
- test/integration/test_running.py
- test/utils.py
Sometimes we need to kill instances instead of gracefully sending SIGTERM.
Closes #312
> --force option for stop command

- CHANGELOG.md
- README.rst
- cli/commands/clean.go
- cli/commands/usage.go
- cli/context/context.go
- cli/running/process.go
- cli/running/process_test.go
- cli/running/processes_set.go
- cli/running/running.go
- test/integration/test_clean.py
- test/utils.py
Sometimes we want to cleanup all instances files (working directories, logs, sockets).
We introduce `cartridge clean` command to do it easily.
Closes #316
> Clean command

- CHANGELOG.md
- README.rst
- cli/commands/create.go
- cli/commands/usage.go
- cli/context/context.go
- cli/create/create.go
- cli/create/templates/templates.go
- test/integration/test_create.py
We need an opportunity to create application using custom templates.
This patch introduces `--from` option for `start` command to specify custom template path.
Closes #321
> Support custom templates

- test/e2e/test_deb.py
- test/e2e/test_docker.py
- test/e2e/test_rpm.py
- test/e2e/test_tgz.py
- test/examples/test_getting_started.py
These tests often fails in GitLab CI by some reasons
(e.g problems with Docker network)
Sometimes we can be sure that our changes didn't affect this,
but this flaky tests are disturb a lot
> Make e2e and example tests xfail

- CHANGELOG.md
- cli/running/process.go
- test/utils.py
If instance process is started in the working directory instead of application directory, it can't require rocks modules without `setsearchroot`. Moreover, code changes aren't applied without `cartridge build`, and it's important for local development.
> Start instance process in the application directory

- cli/repair/app_configs.go
- cli/repair/clusterwide_config.go
- test/clusterwide_conf.py
- test/integration/test_repair.py
When instance is started, but not bootstrapped yet, data directory exists, but cluster-wide configuration don't.
It's a valid case, so it shouldn't cause any error (only if there is no one bootstrapped instance).
> Repair: Fix fail on non bootstrapped instance

- .gitlab-ci.yml
- magefile.go
- test/conftest.py
- test/files/init_ignore_sigterm.lua
- test/files/init_no_cartridge.lua
- test/integration/running/test_clean.py
- test/integration/running/test_log.py
- test/integration/running/test_running.py
- test/project.py
In some tests application files (such as `init.lua`) are rewritten completely.
I think it's time to store such files in a separated directory and provide a function to easily replace files in test projects.
It will be used in #378 to rewrite admin role for different tests.
> Refactor test projects files

- CHANGELOG.md
- cli/commands/gen.go
- cli/common/files.go
- test/integration/cli/test_completion.py
File permissions was discarded on removing duplicate flags (e.g. `--name`, `--name=`).
> Fix bash completion permissions

- CHANGELOG.md
- cli/build/docker.go
Building in docker often fails on GitLab CI because volumes aren't working correctly for default build tmp directory.
The solution is to use `CARTRIDGE_TEMPDIR=. cartridge pack ...`.
I think that this workaround should be shown when building in docker fails.
> Improve build in docker err msg

- CHANGELOG.md
- README.rst
- cli/pack/pack.go
- test/integration/pack/test_pack.py
If `cartridge pack rpm/deb` is called on MacOS without `--use-docker`
flag, the result artifact is broken - it contains rocks and executables
that can't be used on Linux. Now in this case packing fails.
Closes #210
> Fail on cartidge pack RPM and DEB on MacOS without --use-docker

- CHANGELOG.md
- README.rst
- cli/build/docker.go
- cli/build/local.go
- cli/build/post_build.go
- cli/commands/cartridge.go
- cli/common/execute.go
- cli/docker/build.go
- cli/docker/run.go
- cli/pack/deb.go
- cli/pack/docker.go
- go.mod
- test/integration/build/test_build.py
- test/integration/cli/test_version.py
- test/integration/pack/test_pack.py
Now,
--quiet mean no logs
--verbose mean logs + commands/docker output
no flags mean logs + spinner instead of commands/docker output
Spinner is started only for a terminal
Closes #398
> Refactor --quiet flag

- CHANGELOG.md
- cli/admin/common.go
- cli/common/socket.go
- cli/repair/common.go
- cli/repair/patch.go
Before this patch end of Tarantool output wasn't detected correctly.
So all readings from socket failed by timeout (on `n == 0` check).
It leads that read takes time equal to timeout.
Moreover, before each  eval Tarantool greeting was read, so this time
was doubled.
Now `ConnectToTarantoolSocket` function creates a connection, sets read
timeout and reads the greeting once.
`ReadFromConn` function is fixed - end of output is deteced correctly,
by `"\n...\n"` suffix
> Read from Tarantool console socket correctly

- cli/common/utils.go
- cli/repair/clusterwide_config.go
Old function signature required `s.([]interface{})` converting before each call. 
I decided that it should be performed in function itself.
> Refactor common.ConvertToStringsSlice function

- cli/common/socket.go
- cli/common/socket_test.go
This patch fixes two problems:
* function can return non-string error, `tostring(err)` is performed before return now
* parsing result yaml error was confusing, now it shows `Unmarshal` error
> Refactor error handling on socket  eval

- cli/common/files.go
- cli/common/socket.go
- cli/common/utils.go
ReadFromConn function reads plain text from Tarantool connection
These code was inspired by Tarantool console eval
https://github.com/tarantool/tarantool/blob/3bc4a156e937102f23e2157ef88aa6c007759005/src/box/lua/console.lua#L469
By default, Tarantool sends YAML-encoded values as user command response.
In this case the end of output value is `\n...\n`.
What about a case when return string contains this substring?
Everything is OK, since yaml-encoded string is indented via two spaces,
so in fact we never have `\n...\n` in output strings.
If Lua output is set, the end of input is just ";".
And there are some problems.
See https://github.com/tarantool/tarantool/issues/4603
Code is read byte by byte to make parsing output simplier
(in case of box.session.push() response we need to read 2 …
> Refactor reading from Tarantool console

- cli/admin/call.go
- cli/admin/help.go
- cli/admin/list.go
- cli/commands/admin.go
- cli/common/socket.go
- cli/common/tarantool.go
- cli/connect/binary.go
- cli/connect/console.go
- cli/connect/plain_text.go
- cli/repair/common.go
- cli/repair/patch.go
- cli/replicasets/bootstrap_vshard.go
- cli/replicasets/common.go
- cli/replicasets/completion.go
- cli/replicasets/edit_topology.go
- cli/replicasets/membership.go
- cli/replicasets/roles.go
- cli/replicasets/topology_replicasets.go
- cli/replicasets/vshard_group.go
Timeouts is a good approach, but sometimes we have to wait for command
to be completed
For example, connect,enter,admin commands can be used to collect statistics from huge clusters.
Generally, there is no "right" timeout for `edit_topology` calls, so
it's called without timeout.
Some simple things (like fetching Cartridge version) or completion
operations are performed with a little timeout.
> Refactor reading from Tarantool conn timeouts

- test/conftest.py
- test/examples/test_getting_started.py
- test/integration/admin/test_call.py
- test/integration/admin/test_common.py
- test/integration/admin/test_default.py
- test/integration/admin/test_help.py
- test/integration/admin/test_list.py
- test/integration/connect/conftest.py
- test/integration/connect/test_connect.py
- test/integration/repair/test_repair_reload.py
- test/integration/replicasets/conftest.py
- test/integration/replicasets/test_list_replicasets.py
- test/integration/replicasets/test_setup.py
- test/integration/running/test_clean.py
- test/integration/running/test_log.py
- test/integration/running/test_running.py
- test/project.py
- test/utils.py
This patch just reduces copy-paste of computing instances paths in tests
> Refactor computing project paths in tests

- cli/admin/call.go
- cli/admin/help.go
- cli/admin/list.go
- cli/common/socket.go
- cli/common/tarantool.go
- cli/connect/plain_text.go
- cli/repair/common.go
- cli/repair/patch.go
- cli/replicasets/bootstrap_vshard.go
- cli/replicasets/completion.go
- cli/replicasets/edit_topology.go
- cli/replicasets/membership.go
- cli/replicasets/roles.go
- cli/replicasets/topology_replicasets.go
- cli/replicasets/vshard_group.go
Calling `box.session.push` on eval produces additional output that was
interpreted as a eval result before this patch. Now `ReadFromConn` function 
reads all data until non-pushed result is received. By default, pushed messages 
are ignored, but if `PushCallback` function is specified, it's called for each received
message. It's used for `connect` and `enter` commands.
Required for #434
> Allow to pass push callback to eval functions

- CHANGELOG.md
- cli/running/process.go
- cli/running/writer.go
- cli/running/writer_test.go
When instances are started in interactive mode, colorized log writer
is used to prettify log messages. After writing some big amount of data 
to log, this function become waiting forever.
This patch fixes `ColorizedWriter.Write` function to handle number
of bytes that was wrote correctly.
> Fix handling logs on interactive start

- .github/workflows/release.yml
We faced with follwing issue:
```
release failed after 0.02s error=git is currently in a dirty state, please check in your pipeline what can be changing the following files:
?? mage/
```
Skipping validation should solve our problems. However in future
we should provide more proper fix.
Co-authored-by: Elizaveta Dokshina <eldokshina@mail.ru>
> github-ci: add --skip-validate option for goreleaser

- cli/connector/eval_plain_text.go
Before this patch all errors were returned with "Syntax error" prefix, that was wrong in case of runtime errors.
> Remove "Syntax error:" prefix from eval errors

- CHANGELOG.md
- cli/admin/admin.go
- cli/admin/common.go
- cli/admin/common_test.go
- cli/commands/admin.go
- cli/connector/binary.go
- cli/context/context.go
- doc/admin.rst
- test/conftest.py
- test/files/init_admin_funcs.lua
- test/integration/admin/test_call.py
- test/integration/admin/test_common.py
- test/integration/admin/test_default.py
- test/integration/admin/test_help.py
- test/integration/admin/test_list.py
- test/utils.py
Added `--conn, -c` option for `cartridge admin`.
It allows to specify address of instance to run admin function on.
Also added missed `-l` shortcut for `--list` option of `cartridge admin`.
E.g.
```bash
cartridge admin --conn admin:passwd@localhost:3301 probe --help
cartridge admin --conn ./path/to/sock probe --help
```
> Add --conn, -c option for admin

- CHANGELOG.md
- README.rst
- cli/create/templates/cartridge/Dockerfile.build.cartridge
- cli/create/templates/cartridge/Dockerfile.cartridge
- cli/project/dockerfiles.go
- cli/project/dockerfiles_test.go
- test/integration/pack/test_pack.py
- test/integration/pack/test_pack_docker.py
Allowed to use any base docker image for the ``cartridge pack`` command. Closes #469
> Custom centos repo support for `cartridge pack` command added

- CHANGELOG.md
- cli/running/process.go
- test/integration/running/test_running.py
- test/utils.py
Executable with any name (not only ``tarantool``) can run processes. Closes #476
> Remove tarantool process name check

- .github/workflows/tests.yml
Fix unexpected services running on Github Actions
* Stop tarantool example service only if it exists
* Stop Mono service that uses 8084
> CI: Fix unexpected services running on Github Actions

- .github/workflows/release.yml
- .github/workflows/tests.yml
Use ubuntu-18.04 instead of ubuntu-latest since now
it's ubuntu-20.04 which has several problems:
* Mono server starts on 8084 port [1].
* ubuntu-20.04 doesn't have createrepo package
that is used on Release workflow to push packages [2].
[1]: https://github.com/actions/virtual-environments/issues/2821
[2]: https://answers.launchpad.net/createrepo/+question/690448
> CI: Use ubuntu-18.04 on GitHub Actions

- .github/workflows/release.yml
Updating Homebrew formula for Cartridge CLI was performed manually
on each release. Of course, sometimes we forgot to do this. But future 
is here - now we use GitHub Action dawidd6/action-homebrew-bump-formula
[1] to create formula update PR for new tags.
[1]: https://github.com/marketplace/actions/homebrew-bump-formula
> Bump Homebrew formula using GutHub Actions

- go.mod
- go.sum
It wasn't possible to build Cartridge CLI on Apple Silicon 
beacuse `fopsutil` version was too old [1]. Now `gopsutil 3.21.2`
is used.
[1]: https://github.com/Homebrew/homebrew-core/pull/72978#issuecomment-796868671
> Update gopsutil to 3.21.2

- CHANGELOG.md
- cli/connect/console.go
Added cancellation of unfinished expression in ```cartridge enter``` console when pressing ```Ctrl - C```. Closes #473
> Added Ctrl-C behaviour in console

- .github/workflows/tests.yml
- CHANGELOG.md
- README.rst
- cli/pack/docker.go
- cli/project/dockerfiles.go
- cli/project/dockerfiles_test.go
- test/e2e/test_docker.py
- test/files/init_print_environment.lua
- test/integration/pack/test_pack_docker.py
- test/project.py
- test/utils.py
Variables ``TARANTOOL_WORKDIR``, ``TARANTOOL_PID_FILE`` and ``TARANTOOL_CONSOLE_SOCK`` can be customized when packing in docker via ``cartridge pack`` command. Variables ``CARTRIDGE_RUN_DIR`` and ``CARTRIDGE_DATA_DIR`` have also been added. Closes #466
> Ability to customize docker variables

- CHANGELOG.md
- cli/pack/docker.go
- cli/project/dockerfiles.go
- cli/project/dockerfiles_test.go
- test/integration/pack/test_pack_docker.py
It is possible to run an image generated with the ``cartridge pack docker`` command in an unprivileged Kubernetes container. It became possible, because tarantool user now always has ``UID = 1200`` and ``GID = 1200``. Closes #481
> USER instruction in Dockerfile uses UID and GID numbers

- CHANGELOG.md
- cli/create/templates/cartridge/app/roles/custom.lua
- cli/create/templates/cartridge/{{ .Name }}-scm-1.rockspec
Removed a mix of spaces and tabs in ``.rockspec`` file. 
Removed a extra http-endpoint ``metrics`` in ``app.roles.custom.lua.``
Closes #532 and closes #533.
> Cartridge template app improved

- CHANGELOG.md
- cli/commands/pack.go
- test/integration/pack/test_pack.py
Allowed to pack `RPM` and `DEB` packages with ``cartridge pack``
comamnd without default dependencies file.
> Allowed to pack RPM and DEB packages without default dependencies file

- README.rst
There were some warnings while building the docs. Specifically,
about [duplicating target name](https://www.tarantool.io/en/doc/latest/contributing/docs/sphinx-warnings/#duplicate-explicit-target-name) and [malformed hyperlink target](https://www.tarantool.io/en/doc/latest/contributing/docs/sphinx-warnings/#malformed-hyperlink-target).
I also recommend using [tags](https://www.tarantool.io/en/doc/latest/contributing/docs/markup/links/#linking-to-labels-anchors) instead of section names in internal links because they identify a section more accurately.
> fix documentation build warnings

- CHANGELOG.md
- cli/commands/cartridge.go
- cli/commands/usage.go
- cli/commands/version.go
- cli/project/project.go
- cli/version/version.go
- test/integration/cli/test_version.py
``cartridge version`` and ``cartridge --version`` commands
now show Cartridge CLI and Cartridge versions. Moreover, they
can show version of the project rocks.
<details> 
<summary>Example (images) </summary>
</details>
Closes #526
> Change ``cartridge version`` behaviour

- CHANGELOG.md
- cli/create/templates/cartridge/test/helper.lua
- cli/create/templates/cartridge/test/unit/sample_test.lua
Improved tests in ``cartridge create`` template:
* Tests are reduced to the form corresponding to luatest documentation
* ``before_suit`` now remove ``.xlog`` and ``.snap`` files
Closes #546
> Fix issues in cartridge app tests template

- README.rst
> Fix link to information about failover in project README

- .github/workflows/pull-translation.yml
Translated files downloaded from Crowdin with root owner
which the current user can not process. Change user for
translations before process it by cleanup script.
> Fix cleanup translation files

- CHANGELOG.md
- cli/pack/app_dir.go
- cli/pack/pack_test.go
``cartridge pack`` now uses the VERSION file from the
``TARANTOOL_SDK_PATH`` environment variable on 
building in Docker. Closes #580
> Pack in docker (on macos) now using TARANTOOL_SDK_PATH version file

- CHANGELOG.md
- cli/build/docker.go
- cli/commands/pack.go
- cli/commands/usage.go
- cli/common/crypto.go
- cli/context/context.go
- cli/pack/app_dir.go
- cli/pack/docker.go
- cli/pack/tmp_dir.go
- cli/pack/validate.go
- test/integration/pack/test_pack.py
- test/utils.py
Project rocks caching when using ``cartridge pack`` 
command. Closes #559
> Cache .rocks produced on cartridge pack

- CHANGELOG.md
- cli/cluster/instances.go
- cli/replicasets/common.go
- cli/replicasets/membership.go
- test/integration/replicasets/test_bootstrap_vshard.py
- test/integration/replicasets/test_list_replicasets.py
Fixed an incorrect error message when trying to bootstrap 
vshard with out a configured cluster. Closes #595
> Fixed an incorrect error message when trying to bootstrap vshard

- .github/workflows/release.yml
- go.mod
- go.sum
- magefile.publish.go
``update_repo`` script [in tarantool repository](https://github.com/tarantool/tarantool/commit/431c043af63179ae7ac145a5ecaec7bd36db6b43#diff-51435e46617eb7267f50ed8c8f174db3818e65442fcf60600e9824b2b424363e) now uses the ``createrepo_c`` tool 
instead of ``createrepo``. The patch adds this tool to publish S3 pipeline.
> CI: Add build crearepo_s tool to publishS3 job

- CHANGELOG.md
- cli/replicasets/lua/bootstrap_vshard_body.lua
- cli/replicasets/lua/edit_instance_body.lua
- cli/replicasets/lua/edit_replicasets_body_template.lua
- cli/replicasets/lua/get_topology_replicasets_body_template.lua
- test/integration/replicasets/test_setup.py
> Cartridge errors in the ``replicasets`` command are now more readable

- go.mod
- go.sum
This updates x/sys for the sdk and therefor adds support for go 1.17. More info here Homebrew/homebrew-core#83413
Closes #???
> Replace x/sys for go 1.17

- CHANGELOG.md
- cli/docker/build.go
Removed blank lines and replaced with correct  when 
pulling Docker image in ``cartridge pack`` command 
with ``--verbose`` flag.
Closes #627
> Fix displaying of pulling Docker image

- CHANGELOG.md
- go.mod
- go.sum
Vulnerable versions: >= 1.5.0, < 1.5.8
Impact:
In the OCI Distribution Specification version 1.0.0 and prior and
in the OCI Image Specification version 1.0.1 and prior, manifest
and index documents are ambiguous without an accompanying Content-Type
HTTP header. Versions of containerd prior to 1.4.12 and 1.5.8 treat
the Content-Type header as trusted and deserialize the document according
to that header. If the Content-Type header changed between pulls of the
same ambiguous document (with the same digest), the document may be
interpreted differently, meaning that the digest alone is insufficient
to unambiguously identify the content of the image.
> dependency: update containerd version to 1.5.8

- CHANGELOG.md
- go.mod
- go.sum
Vulnerable versions: 1.0.1 and prior
Impact:
In the OCI Image Specification version 1.0.1 and prior, manifest
and index documents are not self-describing and documents with a
single digest could be interpreted as either a manifest or an index.
> dependency: update image-spec version to 1.0.2

- .github/workflows/tests.yml
- CHANGELOG.md
- cli/commands/pack.go
- cli/common/tarantool.go
- cli/common/tarantool_test.go
- cli/common/utils.go
- cli/project/dockerfiles.go
- cli/project/dockerfiles_test.go
- test/e2e/test_deb.py
- test/e2e/test_rpm.py
- test/e2e/test_tgz.py
- test/integration/pack/test_pack.py
- test/utils.py
Reworked version by @DifferentialOrange 
Add struct type for Tarantool version and parsing utility. Struct can be
used to build dependency requirements instead of version string.
Add Tarantool dependency to rpm or deb package only if it is not set up
by user explicitly with --deps or --deps-file. Use version struct
to build minimal and maximal requirements for packages based on new
version policy. Old version policy (2.8 and less) cases are considered
separately. Version struct parsing is strict so "lazy" versions without
number of commits since tag and commit hash (like "2.8.0") are no longer
supported since real Tarantool packages always have them. Use
struct-based approach in integration tests, migrate them to new version
policy.
Tarantool download through the …
> Adapt Cartridge CLI to new release policy

- CHANGELOG.md
- cli/bench/bench.go
- cli/bench/config.go
- cli/bench/space.go
- cli/bench/types.go
- cli/commands/bench.go
- cli/context/context.go
- test/integration/bench/test_bench.py
- test/utils.py
User setup Tarantool single node or cluster and try to understand «How many specific traffic Tarantool can handle on this hardware»
The same official things are for redis, postgresql and aerospike.
Cartridge bench module makes some load for Tarantool.
```
user@cartridge-cli % ./cartridge bench              
Tarantool 2.8.2 (Binary) f4897ffe-98dd-40fc-a6f2-21ca8bb52fe7  
Parameters:
URL: 127.0.0.1:3301
user: guest
connections: 10
simultaneous requests: 10
duration: 10 seconds
key size: 10 bytes
data size: 20 bytes
Data schema
|       key             |       value
------------------------------------------
|       random(10)      |       random(20)
Benchmark start
...
Benchmark stop 
Results:
Success operations:  1169481
Failed  operations:  0
Request count:  1170485
Time (seconds): …
```
> bench: Add benchmark test functionality for single node Tarantool topology

- CHANGELOG.md
- README.dev.md
- magefile.go
To solve #658, I studied how current mage/CI pipeline of this repo works and met some issues, which was also fixed in this PR.
After PR #464 calling `mage clean` was broken. After execution of `mage generateGoCode` FSFile was created in path `cli/create/create_vfsdata_gen.go`, while `mage clean` tried to remove it from `cli/codegen/static/cartridge_vfsdata_gen.go` path.
Before this patch, calling `mage integration`, `mage testExamples` or `mage e2e` failed if `mage GenerateGoCode` hasn't been called yet (explicitly or as `mage lint`, `mage unit` or `mage build` dependency). Now all targets that require generated code explicitly depends on it.
[Documentation](https://magefile.org/dependencies/) says "Dependencies are guaranteed to run exactly once in a single execution of mage", but if …
> Describe local test run, fix some mage issues

- CHANGELOG.md
After PR #629, introduction of Tarantool version as a struct made
Tarantool version check strict (all existing Tarantool versions
are supported).
- Tests
- Documentation
Follows up #619
> Remove outdated changelog entry

- CHANGELOG.md
- cli/create/templates/cartridge/{{ .Name | ToLower }}-scm-1.rockspec
- examples/getting-started-app/README.md
- examples/getting-started-app/README_RUS.md
- examples/getting-started-app/getting-started-app-scm-1.rockspec
- test/integration/cli/test_version.py
- test/integration/connect/test_connect.py
- test/integration/connect/test_enter.py
- test/integration/connect/utils.py
- test/integration/create/test_create.py
- test/integration/replicasets/test_expel.py
Update `cartridge` to `2.7.3` in application template, tests and
examples. Incompatibility with `tarantool` `2.10.0~beta2` or greater is
fixed in `2.7.3`, see [1].
Fixes failing topology edit tests for `tarantool` `2.10.0~beta2` or
greater.
`checks` version `3.1.0` is used in application template, while tests
and examples runs with `3.0.1`. This patch makes versions consistent.
1. https://github.com/tarantool/cartridge/commit/1649b40743bd05f2e71f2ce1ad5b5caf19f864d4
- Documentation (no behavior changes)
Closes #671
> Update cartridge to 2.7.3 in application template

- go.mod
- go.sum
Vulnerable versions: >= 1.5.0, < 1.5.9
Impact:
Containers launched through containerd’s CRI implementation on Linux
systems which use the SELinux security module and containerd versions
since v1.5.0 can cause arbitrary files and directories on the host to
be relabeled to match the container process label through the use of
specially-configured bind mounts in a hostPath volume. This relabeling
elevates permissions for the container, granting full read/write access
over the affected files and directories. Kubernetes and crictl can both
be configured to use containerd’s CRI implementation.
> Update containerd version to 1.5.9

- .github/workflows/release.yml
After #628, package is built with Go 1.17 for test workflow.
At the same time, release workflow still uses Go 1.15.
This patch removes this inconsistency.
- Tests (run with Go 1.17 since #628)
- Changelog (have the entry since #628)
- Documentation (based on #628, there are no visible changes for a user)
Follows up #628
> Update Go to 1.17 in release workflow

- CHANGELOG.md
- cli/pack/app_dir.go
- cli/project/files.go
- test/conftest.py
- test/files/rundir.cartridge.yml
- test/integration/pack/test_pack.py
- test/project.py
Reworked by @DifferentialOrange
``cartridge pack`` command now ignores the contents of ``run_dir``,
``data_dir``, ``log_dir`` directories, if default directories used or
set with ``.cartridge.yml``. Since cartridge-cli do not store info on
flags between runs, if flags like ``--run-dir`` were used, contents
of these directories will not be ignored.
Closes #494
> pack: ignore data, run and log directories

- .github/workflows/release.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- magefile.publish.go
Before merge, someone should set `RWS_AUTH` secret for GitHub Actions.
Change package release policy:
* drop EL6 (CentOS 6.x, RHEL 6.x, CloudLinux 6.x);
* drop Fedora 29;
* drop Ubuntu 14.04 (Trusty);
* drop Debian 8 (Jessie);
* add Fedora 31, 32, 33, 34, 35;
* add Ubuntu 21.04 (Hirsute).
Deprecate workflow_dispatch release flow.
After this patch, package will be published to RWS with curl instead of outdated [update-repo.sh script](https://github.com/tarantool/tarantool/blob/c9e3926e5ae82785c5eb494521c44ba522109e95/tools/update_repo.sh). You can use ``RWS_URL_PART=URL RWS_AUTH=USER:PWD mage PublishRWS`` to publish packages built with goreleaser.
I manually tested it with https://test-tarantool-rws.herokuapp.com/release/modules
Closes #679
> cd: publish to RWS

- CHANGELOG.md
- Updated ``containerd`` version to 1.5.8 to fix the vulnerability bugs:
* https://github.com/advisories/GHSA-c2h3-6mxw-7mvq (container root
directories and some plugins had insufficiently restricted
permissions, allowing otherwise unprivileged Linux users to traverse
directory contents
and execute programs.)
* https://github.com/opencontainers/image-spec/security/advisories/GHSA-77vh-xpmg-72qh
https://github.com/opencontainers/distribution-spec/security/advisories/GHSA-mc8v-mgrf-8f4m
(manifest and index documents are ambiguous without an accompanying Content-Type
HTTP header. Versions of containerd prior to 1.4.12 and 1.5.8 treat
the Content-Type header as trusted and deserialize the document
according to that header.
If the Content-Type header changed between pulls of the same
ambiguous …
> Release 2.11.0

- .github/workflows/tests.yml
This patch cleans up commands used to debug CI/CD in PR #680
> ci: clean up ports log

- README.rst
The [Cartridge CLI doc](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_cli/#command-line-completion) has changed a lot. This PR fixes https://github.com/tarantool/cartridge-cli/issues/673.
> Fix broken links to doc pages

- cli/project/dockerfiles.go
- cli/project/dockerfiles_test.go
Centos 8 mirrors is deprecated now.
Switched to vault repo at cern.ch as a most stable one.
https://www.centos.org/centos-linux-eol
Closes #687
> Fix pack docker with centos 8

- go.mod
- go.sum
Impact:
Systems that rely on digest equivalence for image attestations may be vulnerable to type confusion.
Affected versions:
< 2.8.0
> Update docker version to 2.8.0

- CHANGELOG.md
- go.mod
- go.sum
Vulnerable versions: >= 1.5.0, < 1.5.10
Impact:
A bug was found in containerd where containers launched through
containerd’s CRI implementation with a specially-crafted image
configuration could gain access to read-only copies of arbitrary
files and directories on the host. This may bypass any policy-based
enforcement on container setup (including a Kubernetes Pod Security Policy)
and expose potentially sensitive information. Kubernetes and crictl
can both be configured to use containerd’s CRI implementation.
CVE ID: CVE-2022-23648
GHSA ID: GHSA-crp2-qrr5-8pq7
> Update containerd version to 1.5.10

- CHANGELOG.md
- cli/connect/console.go
The patch adds a workaround for the bug "Terminal does not display command after go-prompt exit" (https://github.com/c-bata/go-prompt/issues/228).
> Fix work with terminal

- CHANGELOG.md
- cli/commands/pack.go
- cli/commands/usage.go
- cli/context/context.go
- cli/pack/common.go
- cli/pack/pack.go
- test/integration/pack/test_pack.py
Added --filename flag to pack command, it allows to explicitly set name of the pack.
Also relaxed --version validation.
> 703. More flexible cartridge pack artifact naming

- doc/commands/pack.rst
- doc/locale/ru/LC_MESSAGES/doc/commands/pack.po
Added documentation for flag '--filename' (command pack).
Part of #703
> pack: add documentation for '--filename'

- doc/installation.rst
Indentation before the line made this line a definition,
and the line before it became a defined term.
> Remove bold formatting from a random line in docs

- go.mod
- go.sum
Cartridge CLI build fails with a checksum mismatch error on Fedora 36:
```
go: downloading github.com/docker/distribution v2.8.0+incompatible
verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch
downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
go.sum:     h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```
2.8.1 release of docker/distribution addresses this issue.
See also distribution/distribution#3590
> Update docker/distribution from 2.8.0 to 2.8.1 to fix go module checksum error

- CHANGELOG.md
- cli/bench/bench.go
- cli/bench/config.go
- cli/bench/requests.go
- cli/bench/space.go
- cli/bench/types.go
- cli/commands/bench.go
- cli/context/context.go
- test/integration/bench/test_bench.py
Patch for load profile with additional select and update operations and with support for benchmark space pre-filling
```
user@cartridge-cli % ./cartridge bench --select=30 --update=30 --insert=40 --fill=100000
Tarantool 2.8.2 (Binary) f4897ffe-98dd-40fc-a6f2-21ca8bb52fe7  
Parameters:
URL: 127.0.0.1:3301
user: guest
connections: 10
simultaneous requests: 10
duration: 10 seconds
key size: 10 bytes
data size: 20 bytes
insert: 40 percentages
select: 30 percentages
update: 30 percentages
Data schema
| key                            | value
| ------------------------------ | ------------------------------
| random(10)                     | random(20)
The pre-filling of the space has started,
because the insert operation is not specified
or there was an explicit instruction for pre-filling
... …
```
> bench: load profile patch (select and update)

- doc/commands/pack/building-in-docker.rst
- doc/locale/ru/LC_MESSAGES/doc/commands/pack/building-in-docker.po
Resolves tarantool/doc#2948
The command `cartridge pack --use-docker` was misleading, running it led to an error. Must have been `cartridge pack TYPE --use-docker`, for example, `cartridge pack rpm --use-docker`.
> Add missing TYPE argument

- doc/commands/start.rst
- doc/locale/ru/LC_MESSAGES/doc/commands/start.po
Markup is broken on the [start](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_cli/commands/start/) doc page:
> Add missing whitespace

- .github/workflows/tests.yml
- magefile.go
- test/integration/admin/test_default.py
- test/integration/cli/test_version.py
- test/integration/create/test_create.py
- test/integration/repair/test_repair_reload.py
- test/integration/replicasets/test_setup.py
- test/make_preparations/test_build_projects.py
- test/project.py
Separated integration tests from linter, unit, e2e and examples checks.
Result: ~15% faster testing.
Added pre-building of slow projects.
Total result: ~40-65% faster.
Closes #690
> tests: make integration testing faster

- .github/workflows/release.yml
- .github/workflows/tests.yml
There is no reason to set Go version as a number: float value can lead to errors due to float precision, and in each place where the value is used it is converted to a string.
- Tests (CI is still green)
- Changelog (not worth to mention)
- Documentation (not worth to mention)
> code-health: set CI/CD Go version as string

- CHANGELOG.md
- cli/connector/connector.go
Now relative path is used instead of real for console socket. It is used to prevent console socket path from being too long.
Before if connection addres was too long it returned an error, now it works.
Needed for [that issue](https://github.com/tarantool/tt/issues/124)
- Tests (CI is still green)
- Changelog (Added)
- Documentation (not worth to mention)
> connector: add fix for long socket paths

- go.mod
- go.sum
Vulnerable versions: < 1.5.13
Impact:
A bug was found in containerd's CRI implementation where programs inside a container can cause the containerd daemon to consume memory without bound during invocation of the ExecSync API. This can cause containerd to consume all available memory on the computer, denying service to other legitimate workloads. Kubernetes and crictl can both be configured to use containerd's CRI implementation; ExecSync may be used when running probes or when executing processes via an "exec" facility.
CVE ID: CVE-2022-31030
GHSA ID: GHSA-5ffw-gxpp-mxpf
> Update containerd version to 1.5.13

- .github/workflows/tests.yml
- .lichen.yaml
- README.dev.md
- magefile.go
We need to check the licenses of modules that came from dependencies. CI should return an error if the licenses are not in the list:
BSD-2
MIT
Apache-2.0
BSD
MPL-2.0
- [not needed] Tests
- [not needed] Changelog
- [Done] Documentation
Closes #737
> ci: add license checker

- doc/installation.rst
Path to installer.sh now must include the version of Tarantool, because installer supports installing several versions.
Issue reported by @ahriman-ru
> Update installation docs

- .github/workflows/tests.yml
The problem is that on Ubuntu 22.04 luarocks v3 from the `tarantool-common` package is installed, but tarantoolctl from tarantool 1.10 uses luarocks v2.
See [1] for more details.
[1] https://github.com/tarantool/tarantool/issues/5429#issuecomment-1336162554
> Fix using tarantoolctl in tests

- CHANGELOG.md
- cli/pack/app_dir.go
- go.mod
- go.sum
Before this commit, file copy operations updated the modification time of the copied files.
It caused a cache invalidation for [cargo](https://doc.rust-lang.org/stable/cargo/).
- Update github.com/otiai10/copy to 1.7.1
- use copy.Copy with `PreserveTimes: true` option
Closes #???
> Preserve file times when copying

- CHANGELOG.md
- cli/pack/app_dir.go
At the moment, the packaging cache is updated after the post-build stage. So if folders such as node_modules, target, etc. are deleted at the post-build stage, they will not get into the cache.
In this commit, the packaging cache update stage runs before the post-build stage.
> Run post-build stage after cache update

- cli/create/templates/cartridge/test/integration/api_test.lua
- cli/create/templates/cartridge/test/unit/sample_test.lua
- test/integration/pack/test_pack_docker.py
Setting before/after hooks through assignment is an outdated way of setting hooks with luatest. It is unsupported with modern hooks like before_test/after_test and doesn't support multiple hooks. Similar issue had been solved in tarantool/tarantool recently [1].
1. https://github.com/tarantool/tarantool/issues/8066
Test group entity is passed to each hook/test. Legacy approach is to use group as global variable, which should work for simple groups, but is invalid for parametrized ones. `cg` variable name was borrowed from luatest README (it is likely a "current group" abbreviation).
> template: luatest best practices

- CHANGELOG.md
- cli/connect/console.go
Fixed crash on \q input in cartridge enter.
In this case, instance returns an empty response,
add a check for this.
Closes #705
> enter: fix crash on `\q`.

- .github/workflows/release.yml
- .github/workflows/tests.yml
The previously used version of go had a number of known security issues. It is time to upgrade.
List of known issues:
```
+-------------------+---------------------------------------+----------------+
|        CVE        |         Infected Version              |  Fix Version   |
+-------------------+---------------------------------------+----------------+
| CVE-2023-24538    | < 1.19.8,1.20.0-0 ≤ Ver < 1.20.3      | 1.19.8,1.20.3  |
| CVE-2023-24540    | < 1.19.9,1.20.0-0 ≤ Ver < 1.20.4      | 1.19.9,1.20.4  |
| CVE-2022-30635    | < 1.17.12,1.18.0-0 ≤ Ver < 1.18.4     | 1.17.12,1.18.4 |
| CVE-2022-28131    | < 1.17.12,1.18.0 ≤ Ver < 1.18.4       | 1.17.12,1.18.4 |
| CVE-2022-30580    | < 1.17.11,1.18.0-0 ≤ Ver < 1.18.3     | 1.17.11,1.18.3 |
| CVE-2023-24534    | < 1.19.8,1.20.0-0 ≤ Ver …
```
> cd: update go version

- README.rst
- doc/index.rst
- doc/migration-to-tt.rst
Add deprecation note on main doc page
Provide instructions on migration to ``tt`` CLI
Part of https://github.com/tarantool/doc/issues/3501
> doc: replace Cartridge CLI with tt CLI

- doc/migration-to-tt.rst
Fix broken code samples in the migration instruction
> doc: fix code markup

- cli/repair/common.go
Added close of file in createFileBackup function.
Found by Svacer
- [not needed ] Tests
- [ not needed] Changelog
- [ not needed] Documentation
> repair: add close of file

- .goreleaser.yml
- CHANGELOG.md
The goreleaser tool runs builds and build hooks in parallel, which can sometimes cause multiple completion generation processes to write to the same file at the same time. To fix this, move the completion script generation outside of the "builds" section.
> cd: fix completion scripts corruption
